application: comp3207-travel-planner-189701
version: 1

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: travel_planner.wsgi.application

libraries:
- name: MySQLdb
  version: "1.2.5"
- name: django
  version: "1.11"
- name: ssl
  version: "2.7.11"

env_variables:
  DJANGO_SETTINGS_MODULE: 'travel_planner.settings'

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
- ^(.*/)?.*\.git.*$