# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='location',
            name='meeting_point',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='photo_url',
            field=models.CharField(max_length=200),
        ),
    ]
