# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20180108_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='finish_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
