# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0005_auto_20180108_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user',
        ),
        migrations.AddField(
            model_name='trip',
            name='followers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
