# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_auto_20180113_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
